[package]
name = "proc_macro_api"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["unbounded_depth"] }
log = "0.4.8"
crossbeam-channel = "0.5.0"
jod-thread = "0.1.1"
memmap2 = "0.3.0"
object = { version = "0.25.3", default-features = false, features = ["std", "read_core", "elf", "macho", "pe"] }
snap = "1.0"

tt = { path = "../tt", version = "0.0.0" }
base_db = { path = "../base_db", version = "0.0.0" }
stdx = { path = "../stdx", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
