[package]
name = "hir_ty"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
itertools = "0.10.0"
arrayvec = "0.7"
smallvec = "1.2.0"
ena = "0.14.0"
log = "0.4.8"
rustc-hash = "1.1.0"
scoped-tls = "1"
chalk-solve = { version = "0.69", default-features = false }
chalk-ir = "0.69"
chalk-recursive = { version = "0.69", default-features = false }
la-arena = { version = "0.2.0", path = "../../lib/arena" }
once_cell = { version = "1.5.0" }

stdx = { path = "../stdx", version = "0.0.0" }
hir_def = { path = "../hir_def", version = "0.0.0" }
hir_expand = { path = "../hir_expand", version = "0.0.0" }
base_db = { path = "../base_db", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
expect-test = "1.1"
tracing = "0.1"
tracing-subscriber = { version = "0.2", default-features = false, features = [
    "env-filter",
    "registry",
] }
tracing-tree = { version = "0.1.4" }
once_cell = { version = "1.5.0", features = ["unstable"] }
