[package]
name = "proc_macro_test"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[lib]
doctest = false

[build-dependencies]
proc_macro_test_impl = { path = "imp", version = "0.0.0" }
toolchain = { path = "../toolchain", version = "0.0.0" }
cargo_metadata = "0.14"
