[package]
name = "syntax"
version = "0.0.0"
description = "Comment and whitespace preserving parser for the Rust language"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-analyzer/rust-analyzer"
edition = "2018"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
itertools = "0.10.0"
rowan = "=0.13.0-pre.7"
rustc_lexer = { version = "725.0.0", package = "rustc-ap-rustc_lexer" }
rustc-hash = "1.1.0"
arrayvec = "0.7"
once_cell = "1.3.1"
indexmap = "1.4.0"
smol_str = { version = "0.1.15", features = ["serde"] }
serde = { version = "1.0.106", features = ["derive"] }

stdx = { path = "../stdx", version = "0.0.0" }
text_edit = { path = "../text_edit", version = "0.0.0" }
parser = { path = "../parser", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }

[dev-dependencies]
rayon = "1"
expect-test = "1.1"
proc-macro2 = "1.0.8"
quote = "1.0.2"
ungrammar = "=1.14"

test_utils = { path = "../test_utils" }
sourcegen = { path = "../sourcegen" }
